// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrprifywweffwaovfwbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlycHJpZnl3d2VmZndhb3Zmd2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzQxOTYsImV4cCI6MjA2NDc1MDE5Nn0.M22SCRMdxrxNtoUzIM8FKitFs-m3keuVqCO6EWUY-Ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);